auto: true
title: "张志敏的技术专栏"
subtitle: "我是一个靠谱的程序员, 目前关注 MonoTouch、 Mono for Android、 Silverlight、  ASP.NET MVC 以及 NHibernate。"
public_url: "http://beginor.github.com"
owner:
  name: "张志敏"
  mail: "beginor(at)qq.com"
  weibo: "http://weibo.com/beginor"
disqus:
  short_name: "beginor-github"
paginate: 10
exclude: [start-jekyll.bat, Github.sln, Github.v11.suo]